# Generated by Django 3.2.6 on 2021-08-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان')),
                ('simple_description', models.CharField(max_length=60, verbose_name='توضیح کوتاه')),
                ('text', models.TextField(verbose_name='متن')),
            ],
        ),
    ]
