# Generated by Django 3.2.6 on 2021-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('simple_description', models.CharField(max_length=120)),
                ('copyright_text', models.CharField(max_length=120)),
            ],
        ),
    ]
