# Generated by Django 3.2.6 on 2021-08-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='copyright_text',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='simple_description',
            field=models.CharField(max_length=40),
        ),
    ]
