# Generated by Django 3.2.6 on 2021-08-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_settings', '0002_auto_20210819_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='simple_description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
